// AUTO-GENERATED by scripts/pack-assets.py - do not edit by hand.
// key -> [sx, sy, w, h] pixel rect within public/assets/objects.png
export const OBJ_RECTS = {
  bld_home: [0, 0, 80, 80],
  bld_lab: [80, 0, 80, 64],
  bld_gym: [160, 0, 80, 64],
  bld_center: [240, 0, 80, 64],
  bld_mart: [320, 0, 80, 64],
  pine: [400, 0, 16, 32],
  pine_big: [416, 0, 32, 32],
  tree_round: [448, 0, 16, 32],
  fountain: [464, 0, 32, 32],
  sign_town: [496, 0, 32, 16],
}

// building key -> [doorLocalCol, doorLocalRow]
export const BUILDING_DOORS = {
  bld_home: [3, 3],
  bld_lab: [3, 3],
  bld_gym: [3, 3],
  bld_center: [3, 3],
  bld_mart: [3, 3],
}
