// AUTO-GENERATED by scripts/pack-assets.py - do not edit by hand.
// key -> [sx, sy, w, h] pixel rect within public/assets/objects.png
export const OBJ_RECTS = {
  bld_home: [0, 0, 80, 95],
  bld_lab: [80, 0, 80, 94],
  bld_gym: [160, 0, 80, 67],
  bld_center: [240, 0, 80, 81],
  bld_mart: [320, 0, 80, 62],
  pine: [400, 0, 16, 32],
  pine_big: [416, 0, 32, 32],
  tree_round: [448, 0, 16, 32],
  fountain: [464, 0, 32, 32],
  sign_town: [496, 0, 32, 16],
  emote_excl: [528, 0, 15, 16],
}

// building key -> [doorLocalCol, doorLocalRow]
export const BUILDING_DOORS = {
  bld_home: [1, 3],
  bld_lab: [1, 3],
  bld_gym: [2, 3],
  bld_center: [2, 3],
  bld_mart: [2, 3],
}
