// Gym interior (projects). Pre-rendered background public/assets/gym-bg.png
// (768x512 = 24x16 tiles @ 32px) generated by scripts/generate-gym-bg.py.
//
// Layout: leader platform rows 2-4 (cols 4-19); project stations at cols 1-3
// and cols 20-22 in rows 6 and 8; battle lane (cols 8-15) runs from row 5 to
// row 12; exit mat at cols 10-12 row 13; side walls at cols 0/23 throughout.
//
// Interactions: face the leader counter (row 3) from row 4 → projects modal;
// face a station from the row below → project dialogue; step onto row 13
// cols 10-12 → warp back to town.

import { INT, DIR } from '../constants.js'

const COLS = 24
const ROWS = 16

const COLLISION_ROWS = [
  '111111111111111111111111', // 0  back wall
  '111111111111111111111111', // 1  back wall
  '111111111111111111111111', // 2  trophy display
  '111111111111111111111111', // 3  leader zone (face from row 4)
  '100000000000000000000001', // 4  platform step — interact with leader
  '100000000000000000000001', // 5  open floor
  '111100000000000000001111', // 6  project stations (cols 1-3 and 20-22)
  '100000000000000000000001', // 7  open floor
  '111100000000000000001111', // 8  project stations (cols 1-3 and 20-22)
  '100000000000000000000001', // 9  open floor
  '100000000000000000000001', // 10 open floor
  '100000000000000000000001', // 11 open floor
  '100000000000000000000001', // 12 open floor
  '111111111100011111111111', // 13 exit mat (cols 10-12 open / step-on)
  '111111111111111111111111', // 14 front wall
  '111111111111111111111111', // 15 front wall
]

const collision = COLLISION_ROWS.map((row) => [...row].map(Number))

const interaction = Array.from({ length: ROWS }, () =>
  Array.from({ length: COLS }, () => 0),
)

function set(c, r, id) {
  interaction[r][c] = id
}

// Leader counter (player at row 4 facing UP hits row 3)
for (const c of [10, 11, 12, 13]) set(c, 3, INT.GYM_LEADER)

// Left project stations (player in rows 7/9 facing UP hits rows 6/8)
for (const c of [1, 2, 3]) set(c, 6, INT.GYM_PROJECT1)
for (const c of [1, 2, 3]) set(c, 8, INT.GYM_PROJECT2)

// Right project stations
for (const c of [20, 21, 22]) set(c, 6, INT.GYM_PROJECT3)
for (const c of [20, 21, 22]) set(c, 8, INT.GYM_PROJECT4)

// Exit mat (step-on)
for (const c of [10, 11, 12]) set(c, 13, INT.GYM_EXIT)

const actions = {
  [INT.GYM_LEADER]: {
    kind: 'dialogue',
    name: 'LEADER',
    lines: [
      'Welcome to my PROJECTS GYM!',
      'Every project here is battle-tested...',
    ],
    thenModal: 'projects',
  },
  [INT.GYM_PROJECT1]: {
    kind: 'dialogue',
    name: 'PROJECT',
    lines: [
      'PKMN PORTFOLIO TOWN',
      'Interactive React portfolio — the one you\'re standing in.',
    ],
  },
  [INT.GYM_PROJECT2]: {
    kind: 'dialogue',
    name: 'PROJECT',
    lines: [
      'Full-stack applications.',
      'React, Node.js, PostgreSQL — shipped end-to-end.',
    ],
  },
  [INT.GYM_PROJECT3]: {
    kind: 'dialogue',
    name: 'PROJECT',
    lines: [
      'Systems & algorithms research.',
      'C++, Python, and data pipelines.',
    ],
  },
  [INT.GYM_PROJECT4]: {
    kind: 'dialogue',
    name: 'PROJECT',
    lines: [
      'Open source contributions.',
      'See the full list in the PROJECTS tab.',
    ],
  },
  [INT.GYM_EXIT]: { kind: 'warp', to: 'town', spawn: 'fromGym', onStep: true },
}

const wanderers = [
  {
    id: INT.NPC4,
    kind: 'npc',
    sprite: 1, // Silver — gym leader
    col: 11,
    row: 3,
    dir: DIR.DOWN,
    static: true,
    lines: ['So — you think you can handle', 'my PROJECTS GYM?'],
    thenModal: 'projects',
  },
  {
    id: INT.MON5,
    kind: 'mon',
    sprite: 2, // Piplup — gym mascot
    col: 12,
    row: 10,
    zone: { c0: 9, r0: 9, c1: 14, r1: 12 },
    moveMs: 380,
    lines: ['Piplup!', '(It seems to guard the challenge floor.)'],
  },
]

export const gymDef = {
  id: 'gym',
  bgSrc: 'assets/gym-bg.png',
  cols: COLS,
  rows: ROWS,
  collision,
  interaction,
  actions,
  wanderers,
  spawns: {
    entry: { col: 11, row: 12, dir: DIR.UP },
    default: { col: 11, row: 12, dir: DIR.UP },
  },
  foregroundRects: [],
}
